Add "jvm_compilation_time_total" counter (CompilationMXBean.getTotalCompilationTime)
prometheus/client_java pull request #659
Opened 2021-05-06 11:37 UTC by rainerjung

The subject says it all. It is one of the few missing metrics from the standard platform MBeans.

2021-05-10 20:24 UTC, fstab commented
Hi thanks a lot for your PRs. I saw them, and I will get back to this as soon as I found time to test this with different Java versions (IBM's J9, etc.).

2021-05-29 22:46 UTC, fstab requested changes
Thanks a lot for your PRs. I have a couple of comments on this one:

Please wrap the code in `addCompilationMetrics()` with
```java
if (compBean != null && compBean.isCompilationTimeMonitoringSupported()) {
    // ...
}
```
to avoid `NullPointerException` and `UnsupportedOperationException`.

Prometheus metrics should have their base unit in their name, so it would be good to rename it to `jvm_compilation_time_seconds_total`.

The new metric should be added to `DefaultExports.register()` (btw when you touch this function you could sort the Exports alphabetically because it's currently hard to check if one is missing).

~~It could be handy to add the compiler (as returned by `compBean.getName()`) as a label, so that the metric looks like `jvm_compilation_time_seconds_total{compiler="j9jit29"}`~~

Update on the last point: it would be more in line with Prometheus conventions to add the compiler to an info metric instead of a label in `jvm_compilation_time_seconds_total`.

2022-07-05 18:01 UTC, dhoard commented
@rainerjung are you planning on implementing the suggestions? ... if not, I'll submit a PR based on the your work and the suggestions.

2022-07-05 18:58 UTC, dhoard commented
@rainerjung new PR https://github.com/prometheus/client_java/pull/797 create.

Since `getTotalCompilationTime()` returns milliseconds, I chose to expose the value as is.

2022-07-06 01:04 UTC, dhoard commented
@rainerjung please close this PR since I have picked up the work. Thanks!

2022-11-16 12:30 UTC, closed without merging